Request connector bugfix.
thingsboard/thingsboard-gateway pull request #480
Opened 2021-02-18 07:30 UTC by dravai

Indentation problem in request connector fixed. There is no need to call TBUtility.get_value() for keys and should check "ts" tag in response json.

2021-02-18 07:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/thingsboard/thingsboard-gateway?pullRequest=480) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/thingsboard/thingsboard-gateway?pullRequest=480) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/thingsboard/thingsboard-gateway?pullRequest=480) it.</sub>

2021-02-22 07:24 UTC, zbeacon requested changes
Hi @dravai ,

Thank you for your participating in project life, but we have to process telemetry and attributes using TBUtility.get_value method to keep compatibility with JSONPath expressions in configuration for keys, instead of getting key from result.

2021-02-22 08:35 UTC, dravai commented
Hi @zbeacon ,

I have the following configuration
`        "telemetry": [
          {
            "key": "ts",
            "type": "long",
            "value": "${scan_at}"
          },
          {
            "key": "sap_order_number",
            "type": "string",
            "value": "${worksheet.sap_order_number}"
          },
          {
            "key": "item_number",
            "type": "string",
            "value": "${product.cikkszam}"
          },
          {
            "key": "quantity",
            "type": "long",
            "value": "${quantity}"
          }
        ]
`
and data from REST request
`{
  'scan_at': 1613980933093, 
  'quantity': 1, 
  'worksheet': {
    'sheet_number': 'SN-09859', 
    'sap_order_number': 'SAP-ON/9746139133', 
   }, 
  'product': {
    'cikkszam': 'CSZ-6322285798', 
    'megnevezes': 'Accessory mattresses time minuses process', 
  }
}
`
TB_Utility.get_value for **quantity** key returns the value of it, instead of the name. In this case return value should be 'quantity' but you get 1. Could you tell me what should I modify in the config to return correct name of quantity key?

Thanks for your help.

2021-02-22 10:09 UTC, zbeacon commented
> Hi @zbeacon ,
> 
> I have the following configuration
> ` "telemetry": [ { "key": "ts", "type": "long", "value": "${scan_at}" }, { "key": "sap_order_number", "type": "string", "value": "${worksheet.sap_order_number}" }, { "key": "item_number", "type": "string", "value": "${product.cikkszam}" }, { "key": "quantity", "type": "long", "value": "${quantity}" } ]`
> and data from REST request
> `{ 'scan_at': 1613980933093, 'quantity': 1, 'worksheet': { 'sheet_number': 'SN-09859', 'sap_order_number': 'SAP-ON/9746139133', }, 'product': { 'cikkszam': 'CSZ-6322285798', 'megnevezes': 'Accessory mattresses time minuses process', } } `
> TBUtility.get_value for **quantity** key returns the value of it, instead of the name. In this case return value should be 'quantity' but I've got 1. Could you tell me what should I modify in the config to get correct name of quantity key?
> 
> Thanks for your help.

Hi @dravai ,

I agree with you, in this case (When you want to use the same key like in the message) TBUtility.get_value using is useless. But it also breaks a case when you want to use value of some received data as a key. Probably we should use converting like in the MQTT uplink converter. What do you think about this?

2021-03-22 15:15 UTC, closed without merging